volumes:
  vault-indexer-db:
    name: vault-indexer-db
services:
  indexer-db:
    container_name: vault-indexer-db
    hostname: vault-indexer-db
    image: postgres:14.9-alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vault_indexer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vault_indexer}
      POSTGRES_DB: ${POSTGRES_DB:-vault-indexer-db}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-vault_indexer}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: always
    volumes:
      - vault-indexer-db:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "5"

  vault-indexer:
    image: scalarorg/vault-indexer:latest
    container_name: vault-indexer
    hostname: vault-indexer
    depends_on:
      indexer-db:
        condition: service_healthy
   
    volumes:
      - ./example/config:/app/config
    # command:
    #   - -config-path
    #   - /app/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "5"
