volumes:
  evms-indexer-db:
    name: evms-indexer-db
services:
  evms-indexer-db:
    container_name: evms-indexer-db
    hostname: evms-indexer-db
    image: postgres:14.9-alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-evms_indexer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-evms_indexer_password}
      POSTGRES_DB: ${POSTGRES_DB:-evms_indexer}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-evms_indexer}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: always
    volumes:
      - evms-indexer-db:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "5"

