volumes:
  evms-indexer-db:
    name: evms-indexer-db
services:
  evms-indexer-db:
    container_name: evms-indexer-db
    hostname: evms-indexer-db
    image: postgres:14.9-alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${INDEXER_POSTGRES_DB:-indexer}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - evms-indexer-db:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "5"

  evms-indexer:
    image: scalarorg/evms-indexer:latest
    container_name: evms-indexer
    hostname: evms-indexer
    depends_on:
      evms-indexer-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@evms-indexer-db:5432/${POSTGRES_DB_EVMS_INDEXER:-indexer}
      - CONFIG_PATH=/app/config
    volumes:
      - ./example/config:/app/config
    # command:
    #   - -config-path
    #   - /app/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "5"
