package abi

const (
	EVENT_EVM_CONTRACT_CALL_APPROVED   = "ContractCallApproved"
	EVENT_EVM_CONTRACT_CALL            = "ContractCall"
	EVENT_EVM_CONTRACT_CALL_WITH_TOKEN = "ContractCallWithToken"
	EVENT_EVM_REDEEM_TOKEN             = "RedeemToken"
	EVENT_EVM_TOKEN_SENT               = "TokenSent"
	EVENT_EVM_COMMAND_EXECUTED         = "Executed"
	EVENT_EVM_TOKEN_DEPLOYED           = "TokenDeployed"
	EVENT_EVM_SWITCHED_PHASE           = "SwitchPhase"
)

var (
	ALL_EVENTS = []string{
		EVENT_EVM_CONTRACT_CALL,
		EVENT_EVM_CONTRACT_CALL_WITH_TOKEN,
		EVENT_EVM_TOKEN_SENT,
		EVENT_EVM_CONTRACT_CALL_APPROVED,
		EVENT_EVM_COMMAND_EXECUTED,
		EVENT_EVM_TOKEN_DEPLOYED,
		EVENT_EVM_SWITCHED_PHASE,
		EVENT_EVM_REDEEM_TOKEN,
	}
)
